version: '3.8'

services:
  app1:
    build:
      context: flight_api/
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    networks:
      - fastapi-network

  app2:
    build:
      context: backend/
      dockerfile: Dockerfile.backend
    ports:
      - "5090:5090"
    networks:
      - fastapi-network

networks:
  fastapi-network:
    driver: bridge

