"""changed typo orders

Revision ID: 108dedb0a99f
Revises: ccc1e9b16194
Create Date: 2024-11-19 01:51:57.826634

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "108dedb0a99f"
down_revision: Union[str, None] = "ccc1e9b16194"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
